### ISSUE TITLE
The "each()" function fails when ODK repeat blocks only have a single item.

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/core-docs#10]
`each()` expects an array, but ODK sends a hash when there's only one item inside a repeat block. Need to build in more flexibility here.

**Comment by svilaboa** [comment]
Hey @taylordowns2000, this might also be the case for multi-selects with one value.

**Comment by taylordowns2000** [comment]
Hi @stephanielitus , @aleksagk , @Natalieflp , @svilaboa , I know you guys are using ODK a lot and may have had issues with only getting a single item from a repeat block. You can now use the `toArray` helper to make sure that ODK gives you an array (which you can use `each(...)` on) for every repeat block, no matter if there's only a single item in that repeat block.

```js
function(state) {
  return toArray( dataValue("[*]")(state) )
}
```

An example of using `toArray(...)` inside an each and a join:
```js
each(
  join(
    function(state) { return toArray(dataValue("rpt_catch")(state)) },
    "$.references[0].id",
    "Id"
  ),
  create("FL_CatchDetails__c", fields(
    field("parent__c", sourceValue("$.data.Id")),
    field("selected_specie__c", sourceValue("$.data.selected_specie")),
    lookup("classification_record__r", "name", "$.data.selected_specie"),
    ...
```
