### ISSUE TITLE
User-friendly interface for editing receipts

### ISSUE THREAD

**Issue by aleksagk** [OpenFn/core-docs#14]
Currently only high-capacity users will feel comfortable editing the submission receipt payloads. Until there is a user-friendly UI, we need to develop error-handling on the destination (Salesforce) side so that system administrators can comfortably manage and correct submissions with errors.

**Comment by taylordowns2000** [comment]
@aleksagk , there are certain receipt bodies that aren't rendering for this new form editor tool. It doesn't affect the data, and users will still be able to use the power editor, but we're trying to take into account all of the various structures we'll see in a JSON payload. Can you alert me if you come across a receipt that doesn't properly render as a form?

Thank you!
