### ISSUE TITLE
History page takes too long to load

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/core-docs#17]
Adding pagination to the history page.

**Comment by Natalieflp** [comment]
I'm having an issue now where the history page is not loading at all. I published a larger volume than usual, could this be an issue?

**Comment by taylordowns2000** [comment]
Hey Natalie. Can you try a hard refresh? It should still work, even if it
takes a while. Hitting control-shift-I will show you the network stats and
you can watch the receipts download on your history page.
