### ISSUE TITLE
Job buttons are hidden underneath OpenFn banner

### ISSUE THREAD

**Issue by carlhughes** [OpenFn/core-docs#19]
The Cancel, Reset Values, and Update buttons are rendered underneath the bottom banner. I have to zoom out in my Firefox to 50% before I can see them.

**Comment by taylordowns2000** [comment]
Apologies, @carlhughes . That's frustrating. We're on it.

Taylor

**Comment by taylordowns2000** [comment]
Hi @carlhughes , I've pushed a short term fix for this that should make your life much easier. It's worth noting that we're rebuilding this page from scratch to add in the `expression helper` tools and eventually the full point-and-click job writing interface ( #18 ). Thanks so much for flagging the issue, and don't hesitate to reach out again.
