### ISSUE TITLE
History/Receipt view: add last modified date 

### ISSUE THREAD

**Issue by aleksagk** [OpenFn/core-docs#26]
Add more system time stamps to allow users to monitor when source data has been modified and resynced

**Comment by taylordowns2000** [comment]
Linked to #2 - yes, will do this.

**Comment by taylordowns2000** [comment]
@aleksagk , @stephanielitus this is complete. Issue #2 stays open, but the two are distinct. Notice we've also added a "notes" feature (at #4 ) that allows a user to comment on anything about a receipt: changes being made, a reason for failure, etc. This is particularly useful for growth and enterprise level orgs who make use of multiple users per inbox.
