### ISSUE TITLE
History: ability to sort/filter submission history by job

### ISSUE THREAD

**Issue by aleksagk** [OpenFn/core-docs#32]

**Comment by aleksagk** [comment]
Filters currently not working - in progress?

**Comment by taylordowns2000** [comment]
@aleksagk , yes... WIP at this point.

**Comment by taylordowns2000** [comment]
Released a filter enabled "activity" page to distinguish between inbound messages (things posted to your inbox) and job runs. @stephanielitus hope this does the trick!

@Natalieflp I know you've been waiting on this. Eager for your feedback.
