### ISSUE TITLE
Logging out and logging in to another account

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/core-docs#35]
When I log out of one openfn bridge account, and then log in to another one, it appears that I am still in the first account for quite a while. I have to click around the site before it eventually stops displaying information from the first account and starts displaying information from the second account.

**Comment by taylordowns2000** [comment]
Thanks, @Natalieflp ! I found that ReceiptFilters and Inboxes were not "purging" themselves on logout, so while you should always have access to your new accounts data, it's possible that you ALSO got access to the data from the last account you were signed in to. Is this what was happening?

I'm testing a fix right now, but it would be super helpful to know if there was anything you saw that didn't match the behaviour I described above.

Also, FWIW, it would be great to keep you on a single username and password (that you don't share with anyone else) and simply grant you access to manage multiple client's inboxes. Let me know if you'd rather use OpenFn this way and I'll connect your own account to manage each client's inbox that you need.

Taylor

**Comment by Natalieflp** [comment]
After I log in to the new account, it returns me to whatever page I was looking at before logging out, and when I click to other tabs it sometimes will still look as if I have never logged out. After one or two clicks it will start loading the new account. I never see data from two different accounts at once, but it does eventually switch from one account to the other. 

I think your suggestion could be useful, are there any reasons you could think of why we wouldn't want multiple client inboxes to be managed from one personal account? If it's easy enough to grant access to new Vera/Client users then I think this could make sense.
