### ISSUE TITLE
Closing window on View Server Logs

### ISSUE THREAD

**Issue by stephanielitus** [OpenFn/core-docs#38]
This is a minor issue, but when clicking View Server Logs button from a Receipt Page, a window opens, and I cannot close the window by clicking the red X in the new window's upper left.  I can close the new window by clicking outside of the new window's area.  It's just not very intuitive to have an X button that doesn't do anything.

I'm using Chrome on a Mac.  Thanks!

<img width="538" alt="screen shot 2016-03-03 at 9 01 10 am" src="https://cloud.githubusercontent.com/assets/17297637/13500256/082b0cf6-e11f-11e5-817f-e81cf38dafc8.png">

**Comment by taylordowns2000** [comment]
@stephanielitus , thanks for logging this! I'll label this an enhancement, and it will actually be sorted out as part of our issue #37 - the error handling framework.

We're making a lot of improvements to how errors are logged, and what tools users have to edit data before "retrying" a job. Will keep you posted!
