### ISSUE TITLE
Erlang error when many submissions were generated during an OpenFn upgrade deployment

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/core-docs#41]
erlang error: :eagain
    (open_fn) web/services/submission_service.ex:11: OpenFn.SubmissionService.process/1
    (elixir) lib/task/supervised.ex:89: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:40: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:240: :proc_lib.init_p_do_apply/3

**Comment by taylordowns2000** [comment]
Thanks @Natalieflp , I've fleshed out the error report a bit and will have a look into it. We haven't seen this happen elsewhere, so it's really helpful that you flagged it.

**Comment by Natalieflp** [comment]
It happened when I published the existing data from ODK aggregate, so many submissions were coming in at once. I re-tried the jobs a few times and nothing seemed to change, I went off and did something else and accidentally tried them again, at which point they became successful

**Comment by taylordowns2000** [comment]
from natalie: In addition to this error https://github.com/OpenFn/core-docs/issues/41, I also received an error that made several submissions fail. You can inspect the receipt here (https://openfn-core.herokuapp.com/receipts/12129/inspect). When I looked at the log it only said, "Logging in as livelyhoods@vera.org." Again, this happened when I published existing data so many submissions came in at once. I re-tried these jobs and they immediately became successful. Both of these errors only occurred from the one job - SA Sign In.

**Comment by taylordowns2000** [comment]
@stuartc , I think this was related to the deploy to add "receipt restore #2 " yesterday. See logs from heroku! The massive influx of receipts appears to have happened right as I deployed.
![image](https://cloud.githubusercontent.com/assets/8732845/13695334/439d0a62-e766-11e5-8970-24e3846ca2c2.png)
