### ISSUE TITLE
vague error upon submission of many ODK forms

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/core-docs#42]
In addition to this error [https://github.com/OpenFn/core-docs/issues/41](url), I also received an error that made several submissions fail. You can inspect the receipt here ([https://openfn-core.herokuapp.com/receipts/12129/inspect](url)). When I looked at the log it only said, "Logging in as livelyhoods@vera.org." Again, this happened when I published existing data so many submissions came in at once. I re-tried these jobs and they immediately became successful. Both of these errors only occurred from the one job - SA Sign In.

**Comment by taylordowns2000** [comment]
@stuartc , I think this was related to the deploy to add "receipt restore #2 " yesterday. See logs from heroku!
![image](https://cloud.githubusercontent.com/assets/8732845/13661664/5f1b8170-e69d-11e5-9176-4c133be21539.png)

**Comment by taylordowns2000** [comment]
Brought relevant error info to #41 , closing.
