### ISSUE TITLE
Duplicate submission errors

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/core-docs#43]
I have a few submissions everyday that appear to have failed, and when I check the reason is because of a duplicate value. When I go to SF I see the record there without any errors. There never appear to be previous attempts, and I've checked to make sure there is only one publisher set up for each job, so I'm not sure at what point the submission made it into Salesforce. 

Here is an example https://www.openfn.org/receipts/12791/inspect receipt for your investigation.

**Comment by taylordowns2000** [comment]
Another ODK user reported getting duplicate submissions sent from ODK. I'll run a query on your receipt history to see if the same payload showed up from ODK twice and get right back to you. Thanks for pointing this out.

**Comment by taylordowns2000** [comment]
Hey @Natalieflp , I ran a quick query and found that ODK sent two copies of the same data:

id | inserted_at
---------|-----------
12791 | 2016-03-11 07:56:41
12787 | 2016-03-11 07:56:41

I checked out your history and [12787](https://www.openfn.org/receipts/12787/inspect) succeeded. I'm going to close this issue for now, and recommend that an issue be opened or investigated on ODK's forum.
