### ISSUE TITLE
Reprocess Message button doesn't always work

### ISSUE THREAD

**Issue by stephanielitus** [OpenFn/core-docs#49]
I can't figure out the rhyme or reason why this happens, but sometime the Reprocess Message button does not work on the first try.  I have to click multiple times, and finally, it starts reprocessing.  Other times, it works just fine on the first try.

**Comment by stephanielitus** [comment]
Today the button is not working at all.  Now this has become more critical as I cannot reprocess modified receipts.

**Comment by taylordowns2000** [comment]
@stephanielitus , it seems that we've done a bad job labeling these buttons. I'll clarify here (for the record) and then get to work on changing the UI so it's more intuitive.

`Reprocess Message` will send the message back through your whole pipeline, checking to see if it matches any filters and then running jobs triggered by those filters. If you're looking at a message that has already matched and triggered a job (which is when folks access that page, 90% of the time) you probably should be clicking `Retry job` (it will say `Run job again` if the previous run was a success) in the red, blue, or green job activity pane.

`Retry job` or `Run job again` will instantly execute the job in question for that receipt, and nothing else. You'll see a spinner come up while it's in progress and see the result in real-time once it's done. This is generally what users should be using to test changes to their job, or run a job on a message again if they've changed the message.

Sorry for the confusion!

Taylor
