### ISSUE TITLE
New dashboard interface becomes unresponsive when selecting a job

### ISSUE THREAD

**Issue by ryanwongsa** [OpenFn/core-docs#50]
When selecting a job to bring up the code Chrome becomes unresponsive and suggests to kill the page or wait. Waiting does not solve the issue and causes major CPU usage and crashes Chrome.
Also I am not sure if this is related but jobs with **auto** *on* do not seem to be running the job automatically anymore and do not appear in **Activity History**.

**Comment by taylordowns2000** [comment]
@ryanwongsa , we use a dependency, `AceEditor`, for the job and receiptViewPower screens. This morning it started looping. We're investigating why and hope to push a fix shortly. Sorry for the inconvenience. All back-end processes will continue to run, uninterrupted.

**Comment by taylordowns2000** [comment]
@ryanwongsa @Natalieflp this is fixed now. Sorry for the delay!

Taylor
