### ISSUE TITLE
OpenFn Documentation and Get Help! links appear in the job editor.

### ISSUE THREAD

**Issue by ryanwongsa** [OpenFn/core-docs#51]
![linksappear](https://cloud.githubusercontent.com/assets/8373287/14777072/e7e38c72-0aca-11e6-961b-4b9aa24cd22c.png)
The links scroll with the editor and overlap with the code.

**Comment by taylordowns2000** [comment]
Thank you, @ryanwongsa ! Fixed z-indexes, deployed to production. You should have the change on your next full refresh of the app.
