### ISSUE TITLE
Error Label

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/core-docs#53]
I have submissions from two months ago that are filtered as failed status, but when I click into them they turn green, but are not reprocessed. I find my submission in Salesforce, why are these being filtered as errors? (example: https://www.openfn.org/projects/aa2d0c80-40b9-498e-9ecb-bfb7c26697c3/receipts/12419/inspect)

**Comment by taylordowns2000** [comment]
Hey @Natalieflp , there's no sensitive data here so I've taken a screengrab of your inspector view for the submission in question. The key is that there are two ways to look at the data, from the perspective of the source message, or from the perspective of a single job run. "Inbox" and "Message Inspector" give you a view from the perspective of the source message... you're able to answer the question: "What happened when this message was received." The "Activity" view shows you every job run that your project has performed... so you'll often have multiple job runs for a single source message. In this particular case, you've got a failed job run, and then a successful one that ran 55 minutes later. In the "inspector view" they're stacked on top of each other, and we show the state of the LAST run by default. From the activity page you can see every run that's taken place.

Below, I've folded out the list of job runs on the Message Inspector. You'll see the failed run beneath that later, successful run. Hope this makes sense!
![image](https://cloud.githubusercontent.com/assets/8732845/14977017/ec9a9a16-1110-11e6-80e7-7e9e605e6ef3.png)

**Comment by Natalieflp** [comment]
That makes sense, but I am wondering if there is a way not to have these show when we filter on errors, since these errors have been "resolved". I would like to move through all of the submissions with errors and ensure that each one has had a successful run, but it is difficult to do that if these receipts will always show up as errors due to their original failure.
