### ISSUE TITLE
Reprocess animation

### ISSUE THREAD

**Issue by Natalieflp** [OpenFn/core-docs#54]
I thought I remembered this bug being logged but couldn't find it: Sometimes when I hit the reprocess button, the animation does not happen (by animation I mean: where the receipt turns blue and there is a processing animation, and then it turns green or red, and updates the time to "a few seconds ago"). I have to reload the page to see if a re-submission was successful

**Comment by taylordowns2000** [comment]
@Natalieflp , Stu just cleaned up the "web socket" that monitors your activity, runs the animation, and updates you when it's finished. Hopefully you won't need to refresh the page anymore. Let me know if this pops up again!

**Comment by Natalieflp** [comment]
Hey Taylor, this is still happening.

**Comment by taylordowns2000** [comment]
@Natalieflp , we found an potential issue where the `web socket` channel was not being joined before the retry button was pressed. Have sorted this out. Please let me know if you see this again. Thank you!

**Comment by taylordowns2000** [comment]
This is still an issue in some cases.

**Comment by taylordowns2000** [comment]
@Natalieflp , we've made additional fixes and are now unable to recreate the bug. Please do let us know if it pops up again. We think it had to do with our running multiple concurrent servers—if your request was processed by one server, the spinner would appear, and if it was processed by another server, it wouldn't appear. The decision to send the request to one server or another is based on real-time server loads, which would explain why this seemed to pop up about 50% of the time, but with no real rhyme or reason.

Really sorry for this inconvenience, and hope it's sorted out!
